### ISSUE TITLE
please remove project

### ISSUE THREAD

**Issue by lnussel** [yast/yast-slide-show#16]
we've moved the slide show to https://github.com/openSUSE/yast-slide-show, I think this one should be removed to avoid confusion.

**Comment by imobach** [comment]
It makes sense. Before proceeding, I've asked in yast-internal mailing list whether anybody is against removing it. Thanks!

**Comment by lnussel** [comment]
any outcome?

**Comment by imobachgs** [comment]
The ideal solution was to move the repository (as Github takes care of redirections). In this case, we have just created a `master_old` branch with the latest state and we've added a notice (and removed all files) in the `master` branch.

Thanks for your patience.
